### ISSUE TITLE
The SUSI Server Doesn't auto boot

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_linux#453] opened 2019-01-19 20:43 UTC
#### Describe the bug
The SUSI Server doesn't autoboot and one has to manually boot it to work on the functionality,

#### To Reproduce
1. Start RasPi after installation
2. Ping localhost:8000

#### Expected behavior
To make it autoboot

#### Additional context
I'd like to take this up

**Comment by hongquan** [comment] 2019-01-20 03:34
It is automatically started, but because of some unknown reason, the startup is not always successful.

**Comment by norbusan** [comment] 2019-05-17 05:53
I think the problem is only with the boot not waiting for the server actually started. The recent changes I made in susi_installer and the systemd script should fix that. I suggest closing this.

**Comment by norbusan** [comment] 2019-12-27 01:14
That has been fixed for quite some time now, closing the issue

**Closed by norbusan** 2019-12-27 01:14 UTC
Labels: SUSI-Server, Systemd
